// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License.

namespace App11
{
    [default_interface]
    runtimeclass Page1 : Microsoft.UI.Xaml.Controls.Page
    {
        Page1();
        Int32 MyProperty;
    }
}
